magephp:
    environments:
        production:
            user: julianadm
            branch: master
            from: ./
            host_path: /var/www/org.libreqs/live/
            releases: 4
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
            hosts:
                - klautspeicher.de
            pre-deploy:
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
                - symfony/cache-warmup: { env: 'dev' }
                - symfony/assets-install: { env: 'dev' }
                - symfony/assetic-dump: { env: 'dev' }
            on-release:
            post-release:
            post-deploy:
